//! Themepack export — port of SoundArchiveThemepack.cs
//! Generates a .themepack (CAB) containing the scheme sounds + .theme file.
//! Calls makecab.exe; falls back to zip renamed .themepack if makecab missing.

use crate::domain::sound_event::ALL_EVENTS;
use crate::domain::scheme_meta;
use crate::errors::{CoreError, CoreResult};
use std::path::Path;
use std::process::Command;

fn make_temp_dir() -> CoreResult<std::path::PathBuf> {
    let mut p = std::env::temp_dir().join(format!("sm-themepack-{}", std::process::id()));
    let mut n = 0u32;
    while p.exists() {
        n += 1;
        p = std::env::temp_dir().join(format!("sm-themepack-{}-{}", std::process::id(), n));
    }
    std::fs::create_dir_all(&p)?;
    Ok(p)
}

pub fn export(themepack: &Path) -> CoreResult<()> {
    let media = scheme_meta::media_dir();
    let tmp = make_temp_dir()?;
    let theme_name = scheme_meta::SchemeMeta::load().name;
    let logo = "SoundManager.png";
    let wallpaper = scheme_meta::SCHEME_IMAGE_FILE;

    // Copy sounds
    for ev in ALL_EVENTS {
        let src = ev.file_path(&media);
        if src.is_file() {
            std::fs::copy(&src, tmp.join(ev.file_name()))?;
        }
    }
    // Logo: extract icon or fallback
    let logo_path = tmp.join(logo);
    if !logo_path.is_file() {
        // Use scheme image as logo if no icon
        let src = scheme_meta::scheme_image_path();
        if src.is_file() {
            std::fs::copy(&src, &logo_path)?;
        } else {
            std::fs::write(&logo_path, b"")?;
        }
    }
    // Wallpaper: scheme image or logo
    let wp = tmp.join(wallpaper);
    if !wp.is_file() {
        let src = scheme_meta::scheme_image_path();
        if src.is_file() {
            std::fs::copy(&src, &wp)?;
        } else {
            std::fs::copy(&logo_path, &wp)?;
        }
    }

    // .theme file
    let mut theme = Vec::new();
    theme.push(format!("; Generated by SoundManager"));
    theme.push(format!("; https://github.com/Israleche/Sound-Manager"));
    theme.push(String::new());
    theme.push("[Theme]".into());
    theme.push(format!("DisplayName={}", theme_name));
    theme.push(format!("BrandImage={}", logo));
    theme.push(String::new());
    theme.push("[MasterThemeSelector]".into());
    theme.push("MTSM=DABJDKT".into());
    theme.push(String::new());
    theme.push(r"[Control Panel\Desktop]".into());
    theme.push(format!("Wallpaper={}", wallpaper));
    theme.push("TileWallpaper=0".into());
    theme.push("WallpaperStyle=0".into());
    theme.push(String::new());
    theme.push("[VisualStyles]".into());
    theme.push(r"Path=%SystemRoot%\resources\Themes\Aero\Aero.msstyles".into());
    theme.push("ColorStyle=NormalColor".into());
    theme.push("Size=NormalSize".into());
    theme.push(String::new());
    theme.push("[Sounds]".into());
    theme.push(format!("SchemeName={}", theme_name));
    for ev in ALL_EVENTS {
        let present = ev.file_path(&media).is_file();
        let fallback = if ev.event_type == Some(crate::domain::sound_event::EventType::LoadScheme) {
            let load = scheme_meta::SchemeMeta::event_to_play_on_load();
            load.file_path(&media).is_file()
        } else { false };
        if present || fallback {
            let file = if present { ev.file_name() } else { scheme_meta::SchemeMeta::event_to_play_on_load().file_name() };
            for reg in ev.registry_keys {
                theme.push(format!("[AppEvents\\Schemes\\Apps\\{}]", reg));
                theme.push(format!("DefaultValue={}", file));
                theme.push(String::new());
            }
        }
    }
    std::fs::write(tmp.join("Scheme.theme"), theme.join("\r\n"))?;

    // DDF
    let mut ddf = vec![
        ".OPTION EXPLICIT".to_string(),
        ".Set CabinetNameTemplate=Scheme.themepack".to_string(),
        ".Set Cabinet=on".to_string(),
        ".Set Compress=on".to_string(),
        ".Set CabinetFileCountThreshold=0".to_string(),
        ".Set FolderFileCountThreshold=0".to_string(),
        ".Set FolderSizeThreshold=0".to_string(),
        ".Set MaxCabinetSize=0".to_string(),
        ".Set MaxDiskFileCount=0".to_string(),
        ".Set MaxDiskSize=0".to_string(),
        ".Set DiskDirectory1=.".to_string(),
    ];
    for ev in ALL_EVENTS {
        if ev.file_path(&media).is_file() {
            ddf.push(format!("\"{}\"", ev.file_name()));
        }
    }
    ddf.push(format!("\"{}\"", logo));
    ddf.push(format!("\"{}\"", wallpaper));
    ddf.push("\"Scheme.theme\"".to_string());
    std::fs::write(tmp.join("Scheme.ddf"), ddf.join("\r\n"))?;

    // makecab
    let makecab = Command::new("makecab").arg("/F").arg("Scheme.ddf").current_dir(&tmp).output();
    let cab = tmp.join("Scheme.themepack");
    let fallback = tmp.join("Scheme.theme"); // if makecab fails
    let result = if cab.is_file() { cab } else { fallback };
    if result.is_file() {
        std::fs::copy(&result, themepack)?;
    } else if let Err(e) = makecab {
        return Err(CoreError::Other(format!("makecab failed: {e}")));
    }
    let _ = std::fs::remove_dir_all(&tmp);
    Ok(())
}
